apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name	: ingressfileget
 
spec:
  ingressClassName: nginx
  rules : 
  - host : get1.hastapanda.site
    http :
      paths :
      - path : "/"
        pathType: Prefix
        backend :
          service :
            name : get-service   
            port :
              number : 80

  