apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name	: ingressfiledelete
  
spec:
  ingressClassName: nginx
  rules : 
  - host : delete11.hastapanda.site
    http :
      paths :
      - path : "/"
        pathType: Prefix
        backend :
          service :
            name : delete-service   
            port :
              number : 80