apiVersion : networking.k8s.io/v1
kind : Ingress
metadata :
  name	: ingressfileadd
      
spec:
  ingressClassName: nginx
  rules : 
  - host :  add11.hastapanda.site
    http :
      paths :
      - path : "/"
        pathType: Prefix
        backend :
          service :
            name : add-service   
            port :
              number : 80