apiVersion : apps/v1
kind : Deployment
metadata :
  name : todoget
spec :
  replicas : 3
  selector :
    matchExpressions :
    - key : app
      operator: In
      values : 
      - get
  strategy :
    rollingUpdate	:
      maxSurge : 25%
      maxUnavailable : 25%
  template :
    metadata:
      labels:
        app : get
    spec:
      containers:
      - name: deepakadd
        image: deepak1247/dockerfiles_todo1:3.0
        ports:
        - containerPort: 8000
        env : 
        - name : CONNECTION_STRING
          value : Driver={ODBC Driver 17 for SQL Server};Server=tcp:dsddsds.database.windows.net,1433;Database=deepdab;Uid=deepak;Pwd={Bigbluff$};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;
           